In [102]:
import numpy as np

In [124]:
w = 10
h = 12

p1 = np.array([6, 5])
p2 = np.array([9, 2])
direction = p2 - p1

In [125]:
x = np.tile(np.array(np.arange(0, w)), (h, 1)).T
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [126]:
y = np.tile(np.array(np.arange(0, h)), (w, 1))
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [127]:
xy = np.concatenate((x[:,:,None], y[:,:,None]), axis=2)
xy.shape

(10, 12, 2)

In [128]:
line_points = xy - p1

upper_proj = np.dot(line_points, direction)
lower_proj = np.linalg.norm(direction) ** 2
proj = upper_proj / lower_proj
proj_points = proj[..., None] * np.tile(direction, (w, h, 1))

In [129]:
result = np.floor(np.linalg.norm(proj_points - line_points, axis=2))
result

array([[7., 7., 6., 5., 4., 4., 3., 2., 2., 1., 0., 0.],
       [7., 6., 5., 4., 4., 3., 2., 2., 1., 0., 0., 0.],
       [6., 5., 4., 4., 3., 2., 2., 1., 0., 0., 0., 1.],
       [5., 4., 4., 3., 2., 2., 1., 0., 0., 0., 1., 2.],
       [4., 4., 3., 2., 2., 1., 0., 0., 0., 1., 2., 2.],
       [4., 3., 2., 2., 1., 0., 0., 0., 1., 2., 2., 3.],
       [3., 2., 2., 1., 0., 0., 0., 1., 2., 2., 3., 4.],
       [2., 2., 1., 0., 0., 0., 1., 2., 2., 3., 4., 4.],
       [2., 1., 0., 0., 0., 1., 2., 2., 3., 4., 4., 5.],
       [1., 0., 0., 0., 1., 2., 2., 3., 4., 4., 5., 6.]])

In [116]:
result.shape

(1200, 2000)